/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ActionVerifierInterface extends Interface {
  getFunction(
    nameOrSignature: "verifiedActions" | "verifyAction"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "verifiedActions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAction",
    values: [BytesLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "verifiedActions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAction",
    data: BytesLike
  ): Result;
}

export interface ActionVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): ActionVerifier;
  waitForDeployment(): Promise<this>;

  interface: ActionVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  verifiedActions: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  verifyAction: TypedContractMethod<
    [_proof: BytesLike, _location: string],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "verifiedActions"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyAction"
  ): TypedContractMethod<
    [_proof: BytesLike, _location: string],
    [boolean],
    "nonpayable"
  >;

  filters: {};
}
