import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ThemeProvider from "@/components/ThemeProvider";
import Link from "next/link";
import "./styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Envolve",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black dark:bg-black dark:text-white`}
      >
        <ThemeProvider>
          <nav className="flex items-center justify-between px-6 py-4 bg-gray-100 dark:bg-gray-900 shadow-md">
            <div className="text-xl font-bold">Envolve</div>
            <div className="flex gap-6 text-base font-medium">
              <Link
                href="/"
                className="hover:underline hover:underline-offset-4 transition-colors"
              >
                Home
              </Link>
              <Link
                href="/about"
                className="hover:underline hover:underline-offset-4 transition-colors"
              >
                About
              </Link>
            </div>
          </nav>

          <main className="px-6 py-8">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
