import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black dark:bg-black dark:text-white`}
      >
        <nav className="flex items-center justify-between px-6 py-4 bg-gray-100 dark:bg-gray-900 shadow-md">
          <div className="text-xl font-bold">Envolve</div>
          <div className="flex gap-6 text-base font-medium">
            <Link
              href="/"
              className="hover:underline hover:underline-offset-4 transition-colors"
            >
              Home
            </Link>
            <Link
              href="/about"
              className="hover:underline hover:underline-offset-4 transition-colors"
            >
              About
            </Link>
            {/* Add more links here */}
          </div>
        </nav>

        <main className="px-6 py-8">{children}</main>
      </body>
    </html>
  );
}
